### ISSUE TITLE
Bug Report: there is something wrong with the building 

### ISSUE THREAD

**Issue by ghost** [isophoro/Friday-Night-Fever#1]
the Jukeboxstate.hx is bugged 
here is the problem
source/JukeboxState.hx:10: characters 8-15 : Module Discord does not define type Discord
source/JukeboxState.hx:47: characters 9-22 : Unknown identifier : discordClient

thats the problem if you can please fix the bug 
bye and have a nice day

**Comment by rifxii** [comment]
Are you trying to compile the mod on Mac or Linux by any chance? I believe I fixed it in the latest commit if you want to try building it again.

**Comment by ghost** [comment]
by mac

**Comment by ghost** [comment]
how did you fix it?

**Comment by ghost** [comment]
i will let you know if i could build it

**Comment by ghost** [comment]
see i have a website where i mac stuff on itch.io and i wanted to help mac users like me you can look if you want 
my itch.io : https://jonnycat.itch.io/mods-mac-versions 
you can look on it if you want too

**Comment by ghost** [comment]
there we go now its fixed thank you soo much

**Comment by rifxii** [comment]
no problem! glad its fixed
